language:
  c
script:
  make test
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
notifications:
  email:
    - sinistersnare@gmail.com
